table sales_items
	lineageTag: cd2c16ac-20cc-4c0c-80c9-9a6c45d538d4

	column sale_item_id
		dataType: string
		lineageTag: bb9a1549-eb19-4f6d-9f8f-335a722141c1
		summarizeBy: none
		sourceColumn: sale_item_id

		annotation SummarizationSetBy = Automatic

	column sale_id
		dataType: string
		lineageTag: d44346b0-3fbf-48f3-a246-6424f5ddc4f0
		summarizeBy: none
		sourceColumn: sale_id

		annotation SummarizationSetBy = Automatic

	column product_id
		dataType: string
		lineageTag: 05af5bc4-d0fe-4f0a-aeb6-e65b4136a1f1
		summarizeBy: none
		sourceColumn: product_id

		annotation SummarizationSetBy = Automatic

	column quantity
		dataType: int64
		formatString: 0
		lineageTag: 198ec7f1-2a36-4a26-b798-5af906615b56
		summarizeBy: sum
		sourceColumn: quantity

		annotation SummarizationSetBy = Automatic

	column unit_price
		dataType: int64
		formatString: 0
		lineageTag: 83492288-6d74-44b3-9a8b-6c9ad2c40f73
		summarizeBy: sum
		sourceColumn: unit_price

		annotation SummarizationSetBy = Automatic

	column line_total
		dataType: int64
		formatString: 0
		lineageTag: c32e5a10-2602-4667-bfcc-11a1df18961a
		summarizeBy: sum
		sourceColumn: line_total

		annotation SummarizationSetBy = Automatic

	partition sales_items = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\user\׳“׳¡׳™\׳¢׳‘׳•׳“׳”\sales_items.csv"),[Delimiter=",", Columns=6, Encoding=1255, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"sale_item_id", type text}, {"sale_id", type text}, {"product_id", type text}, {"quantity", Int64.Type}, {"unit_price", Int64.Type}, {"line_total", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

